// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LoansManager.DAL.Migrations
{
    public partial class AddLoansTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Loans",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CommitmentValue = table.Column<decimal>(nullable: false),
                    IsRepaid = table.Column<bool>(nullable: false),
                    StartDate = table.Column<DateTime>(nullable: false),
                    RepaidDate = table.Column<DateTime>(nullable: true),
                    LenderId = table.Column<string>(nullable: true),
                    BorrowerId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Loans", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Loans_Users_BorrowerId",
                        column: x => x.BorrowerId,
                        principalTable: "Users",
                        principalColumn: "UserName",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Loans_Users_LenderId",
                        column: x => x.LenderId,
                        principalTable: "Users",
                        principalColumn: "UserName",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Loans_BorrowerId",
                table: "Loans",
                column: "BorrowerId");

            migrationBuilder.CreateIndex(
                name: "IX_Loans_LenderId",
                table: "Loans",
                column: "LenderId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Loans");
        }
    }
}
